[versions]
contracts-version = "[2.5.2,3.0.0)"
concurrency-version = "[1.3.1,2.0.0)"
metalog-version = "[1.2.3,2.0.0)"
protobuf-plugin-version = "0.9.5"
grpc-version = "1.76.0"
protobuf-version = "3.25.8"

[libraries]
contracts-api = { module = "io.github.jonloucks.contracts:contracts-api", version.ref = "contracts-version" }
contracts-test = { module = "io.github.jonloucks.contracts:contracts-test", version.ref = "contracts-version" }
contracts = { module = "io.github.jonloucks.contracts:contracts", version.ref = "contracts-version" }
concurrency-api = { module = "io.github.jonloucks.concurrency:concurrency-api", version.ref = "concurrency-version" }
concurrency-test = { module = "io.github.jonloucks.concurrency:concurrency-test", version.ref = "concurrency-version" }
concurrency = { module = "io.github.jonloucks.concurrency:concurrency", version.ref = "concurrency-version" }
metalog-api = { module = "io.github.jonloucks.metalog:metalog-api", version.ref = "metalog-version" }
metalog-test = { module = "io.github.jonloucks.metalog:metalog-test", version.ref = "metalog-version" }
metalog = { module = "io.github.jonloucks.metalog:metalog", version.ref = "metalog-version" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf-version" }
grpc-protoc = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc-version"}
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc-version"}
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc-version"}
grpc-services = { module = "io.grpc:grpc-services", version.ref = "grpc-version"}
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc-version"}
grpc-testing = { module = "io.grpc:grpc-testing", version.ref = "grpc-version"}
grpc-inprocess = { module = "io.grpc:grpc-inprocess", version.ref = "grpc-version"}
